/**
 * Regional Seed Database for Top Global & Indian Destinations
 *
 * Guarantees that iconic landmarks are NEVER missed even during API latency,
 * network hiccups, or AI quota rate-limiting (429).
 */

const SEEDS_MAP = {
  ladakh: [
    "Pangong Tso Lake",
    "Nubra Valley (Hunder Sand Dunes)",
    "Khardung La Pass",
    "Magnetic Hill Ladakh",
    "Thiksey Monastery",
    "Leh Palace",
    "Shanti Stupa Leh",
    "Hemis Monastery & Museum",
    "Diskit Monastery & Giant Buddha",
    "Tso Moriri Lake",
    "Hall of Fame Leh",
    "Sangam Point (Indus & Zanskar Confluence)",
    "Alchi Monastery",
    "Shey Palace and Monastery",
    "Likir Monastery",
    "Spituk Monastery",
    "Gurudwara Pathar Sahib",
    "Hanle Dark Sky Observatory",
    "Zanskar Valley & Phugtal Monastery",
    "Lamayuru Monastery (Moonland)",
  ],
  leh: [
    "Leh Palace",
    "Shanti Stupa Leh",
    "Pangong Tso Lake",
    "Thiksey Monastery",
    "Hall of Fame Leh",
    "Magnetic Hill",
    "Khardung La Pass",
    "Nubra Valley (Hunder)",
    "Hemis Monastery",
    "Shey Palace",
    "Spituk Gompa",
    "Gurudwara Pathar Sahib",
    "Sankar Gompa",
    "Zorawar Fort Leh",
    "Sindhu Ghat Leh",
    "Stok Palace Museum",
  ],
  kashmir: [
    "Dal Lake & Shikara Ride",
    "Shalimar Bagh Mughal Garden",
    "Nishat Bagh Srinagar",
    "Gulmarg Gondola & Apharwat Peak",
    "Betaab Valley Pahalgam",
    "Aru Valley Pahalgam",
    "Baisaran Valley (Mini Switzerland)",
    "Sonamarg Thajiwas Glacier",
    "Shankaracharya Temple Srinagar",
    "Pari Mahal Srinagar",
    "Indira Gandhi Memorial Tulip Garden",
    "Doodhpathri Meadow of Milk",
    "Hazratbal Shrine Srinagar",
    "Chashme Shahi Garden",
    "Sinthan Top",
  ],
  srinagar: [
    "Dal Lake & Houseboats",
    "Shalimar Bagh",
    "Nishat Bagh",
    "Shankaracharya Temple",
    "Pari Mahal",
    "Indira Gandhi Tulip Garden",
    "Hazratbal Dargah",
    "Chashme Shahi",
    "Hari Parbat Fort",
    "Nigeen Lake",
    "Jamia Masjid Srinagar",
    "Dalgate Bridge & Floating Market",
  ],
  shimla: [
    "The Ridge & Mall Road Shimla",
    "Jakhu Temple & Giant Hanuman Statue",
    "Kufri Adventure Park",
    "Christ Church Shimla",
    "Viceregal Lodge (Rashtrapati Niwas)",
    "Tara Devi Temple",
    "Chadwick Falls",
    "Summer Hill Shimla",
    "Annandale Ground & Army Museum",
    "Gaiety Heritage Cultural Complex",
    "Scandal Point Mall Road",
    "Mashobra Green Valley",
  ],
  rishikesh: [
    "Lakshman Jhula",
    "Ram Jhula",
    "Triveni Ghat Maha Aarti",
    "Parmarth Niketan Ashram",
    "Beatles Ashram (Chaurasi Kutia)",
    "Neer Garh Waterfall",
    "Shivpuri River Rafting",
    "Tera Manzil Temple (Trimbakeshwar)",
    "Jumpin Heights Adventure Zone",
    "Patna Waterfalls",
    "Vashishta Gufa Cave",
    "Kunjapuri Devi Temple Sunrise Viewpoint",
  ],
  haridwar: [
    "Har Ki Pauri Ganga Aarti",
    "Mansa Devi Temple Cable Car",
    "Chandi Devi Temple",
    "Maya Devi Temple",
    "Daksha Mahadev Temple Kankhal",
    "Shanti Kunj Gayatri Parivar",
    "Bharat Mata Mandir",
    "Pawan Dham",
    "Rajaji National Park",
  ],
  udaipur: [
    "City Palace Udaipur",
    "Lake Pichola Boat Ride",
    "Jag Mandir Island Palace",
    "Saheliyon-ki-Bari",
    "Jagdish Temple",
    "Sajjangarh Monsoon Palace",
    "Fateh Sagar Lake & Nehru Park",
    "Bagore Ki Haveli (Dharohar Dance)",
    "Vintage and Classic Car Museum",
    "Karni Mata Ropeway Viewpoint",
    "Ahar Cenotaphs",
    "Bharo Ka Mandir",
  ],
  jodhpur: [
    "Mehrangarh Fort",
    "Jaswant Thada Memorial",
    "Umaid Bhawan Palace & Museum",
    "Clock Tower & Sardar Market",
    "Mandore Gardens",
    "Rao Jodha Desert Rock Park",
    "Toorji Ka Jhalra Stepwell",
    "Kaylana Lake",
    "Chamunda Devi Temple",
    "Balsamand Lake & Palace",
  ],
  jaisalmer: [
    "Jaisalmer Fort (Sonar Qila)",
    "Sam Sand Dunes & Camel Safari",
    "Patwon Ki Haveli",
    "Gadisar Lake",
    "Nathmal Ki Haveli",
    "Salim Singh Ki Haveli",
    "Kuldhara Abandoned Ghost Village",
    "Tanot Mata Temple",
    "Longewala War Memorial",
    "Thar Heritage Museum",
    "Bada Bagh Cenotaphs",
  ],
  bangalore: [
    "Bangalore Palace",
    "Lalbagh Botanical Garden",
    "Cubbon Park",
    "Bannerghatta Biological Park",
    "ISKCON Temple Bangalore",
    "Tipu Sultan's Summer Palace",
    "Vidhana Soudha",
    "Visvesvaraya Industrial & Technological Museum",
    "Commercial Street & Brigade Road",
    "HAL Heritage Centre and Aerospace Museum",
    "Bull Temple (Nandi Temple Basavanagudi)",
    "Wonderla Amusement Park Bangalore",
  ],
  bengaluru: [
    "Bangalore Palace",
    "Lalbagh Botanical Garden",
    "Cubbon Park",
    "Bannerghatta Biological Park",
    "ISKCON Temple Bangalore",
    "Tipu Sultan's Summer Palace",
    "Vidhana Soudha",
    "Visvesvaraya Museum",
    "HAL Aerospace Museum",
    "UB City Mall",
  ],
  mumbai: [
    "Gateway of India",
    "Marine Drive (Queen's Necklace)",
    "Elephanta Caves",
    "Chhatrapati Shivaji Maharaj Terminus (CSMT)",
    "Bandra-Worli Sea Link",
    "Siddhivinayak Temple Prabhadevi",
    "Haji Ali Dargah",
    "Juhu Beach",
    "Colaba Causeway",
    "Sanjay Gandhi National Park & Kanheri Caves",
    "Girgaon Chowpatty",
    "Prince of Wales Museum (CSMVS)",
  ],
  delhi: [
    "Red Fort (Lal Qila)",
    "Qutub Minar",
    "India Gate & Kartavya Path",
    "Humayun's Tomb",
    "Lotus Temple (Bahá'í House of Worship)",
    "Swaminarayan Akshardham Temple",
    "Jama Masjid Delhi",
    "Rashtrapati Bhavan",
    "Chandni Chowk & Khari Baoli",
    "Lodhi Garden",
    "Gurudwara Bangla Sahib",
    "National Gallery of Modern Art",
  ],
  kolkata: [
    "Victoria Memorial",
    "Howrah Bridge",
    "Dakshineswar Kali Temple",
    "Kalighat Kali Temple",
    "Indian Museum Kolkata",
    "Science City Kolkata",
    "Princep Ghat & Hooghly Riverfront",
    "Park Street",
    "Eco Park New Town",
    "Belur Math",
    "St. Paul's Cathedral Kolkata",
    "Marble Palace Mansion",
  ],
  hyderabad: [
    "Charminar",
    "Golconda Fort & Sound and Light Show",
    "Ramoji Film City",
    "Hussain Sagar Lake & Giant Buddha Statue",
    "Chowmahalla Palace",
    "Salar Jung Museum",
    "Birla Mandir Hyderabad",
    "Qutb Shahi Tombs",
    "Nehru Zoological Park",
    "Laad Bazaar (Choodi Bazaar)",
  ],
  chennai: [
    "Marina Beach",
    "Kapaleeshwarar Temple Mylapore",
    "San Thome Cathedral Basilica",
    "Fort St. George & Museum",
    "Government Museum Egmore",
    "Guindy National Park",
    "Edward Elliot's Beach (Besant Nagar)",
    "Valluvar Kottam",
    "DakshinaChitra Heritage Museum",
    "Mahabalipuram Shore Temple",
  ],
  ooty: [
    "Government Botanical Garden Ooty",
    "Doddabetta Peak",
    "Ooty Lake & Boathouse",
    "Nilgiri Mountain Railway (Toy Train)",
    "Government Rose Garden Ooty",
    "Pykara Waterfalls & Pykara Lake",
    "Avalanche Lake",
    "Emerald Lake Ooty",
    "Shooting Point (Pine Forest)",
    "Tea Museum & Factory Ooty",
    "Kamraj Sagar Dam (Sandynalla Reservoir)",
    "Thread Garden Ooty",
  ],
  coorg: [
    "Abbey Falls",
    "Raja's Seat Viewpoint",
    "Namdroling Monastery (Golden Temple Bylakuppe)",
    "Talakaveri (Origin of River Cauvery)",
    "Dubare Elephant Camp",
    "Mandalpatti Peak (4x4 Jeep Safari)",
    "Iruppu Falls (Lakshmana Tirtha Falls)",
    "Madikeri Fort & Palace",
    "Coffee Plantation Walks & Tours",
    "Chelavara Falls",
    "Honnamana Kere Lake",
    "Brahmagiri Wildlife Sanctuary",
  ],
  kodagu: [
    "Abbey Falls",
    "Raja's Seat",
    "Namdroling Monastery",
    "Talakaveri",
    "Dubare Elephant Camp",
    "Mandalpatti Peak",
    "Iruppu Falls",
    "Madikeri Fort",
  ],
  wayanad: [
    "Banasura Sagar Dam (Largest Earthen Dam in India)",
    "Chembra Peak & Heart-shaped Lake",
    "Edakkal Caves (Prehistoric Rock Engravings)",
    "Soochipara Falls (Sentinel Rock Waterfalls)",
    "Wayanad Wildlife Sanctuary (Muthanga)",
    "Pookode Lake",
    "Meenmutty Waterfalls",
    "Lakkidi View Point",
    "Thirunelli Temple (Thekkan Kasi)",
    "Karapuzha Dam",
    "Kuruva Dweep (Kuruvadweep Island)",
    "Phantom Rock",
  ],
  amritsar: [
    "Golden Temple (Sri Harmandir Sahib)",
    "Wagah Border Beating Retreat Ceremony",
    "Jallianwala Bagh Memorial",
    "Partition Museum Town Hall",
    "Gobindgarh Fort",
    "Durgiana Temple (Lakshmi Narayan)",
    "Sri Ram Tirath Ashram",
    "Hall Bazaar Shopping",
    "Sada Pind Cultural Heritage Village",
    "Akal Takht",
  ],
  hampi: [
    "Virupaksha Temple Hampi",
    "Vijaya Vittala Temple & Stone Chariot",
    "Matanga Hill Sunrise Viewpoint",
    "Lotus Mahal & Zenana Enclosure",
    "Elephant Stables Hampi",
    "Hemakuta Hill Temples",
    "Queen's Bath Hampi",
    "Tungabhadra River & Coracle Boat Ride",
    "Hazara Rama Temple",
    "Anjaneya Hill (Birthplace of Hanuman / Kishkindha)",
    "Sanapur Lake",
    "Archaeological Museum Kamalapur",
  ],
  pondicherry: [
    "Promenade Beach & Rock Beach",
    "Sri Aurobindo Ashram",
    "Auroville & Matrimandir",
    "French War Memorial",
    "Paradise Beach & Chunnambar Boat House",
    "White Town (French Quarter)",
    "Basilica of the Sacred Heart of Jesus",
    "Serenity Beach",
    "Auroville Beach",
    "Immaculate Conception Cathedral",
    "Pondicherry Museum",
    "Botanical Garden Puducherry",
  ],
  puducherry: [
    "Promenade Beach",
    "Aurobindo Ashram",
    "Auroville & Matrimandir",
    "Paradise Beach",
    "White Town Heritage Walk",
    "Sacred Heart Basilica",
    "Serenity Beach",
    "Chunnambar Boat House",
  ],
  shillong: [
    "Umiam Lake (Barapani Lake)",
    "Elephant Falls",
    "Shillong Peak Viewpoint",
    "Don Bosco Museum of Indigenous Cultures",
    "Ward's Lake (Pollok Lake)",
    "Laitlum Canyons",
    "Police Bazar Market",
    "Lady Hydari Park",
    "Cathedral of Mary Help of Christians",
    "Sweet Falls Shillong",
    "Air Force Museum Shillong",
    "Mawphlang Sacred Forest",
  ],
  meghalaya: [
    "Double Decker Living Root Bridge (Nongriat)",
    "Nohkalikai Falls (Tallest Plunge Waterfall in India)",
    "Seven Sisters Falls (Nohsngithiang Falls)",
    "Mawsmai Cave Cherrapunji",
    "Dawki River (Umngot Crystal Clear River)",
    "Mawlynnong Cleanest Village in Asia",
    "Arwah Cave",
    "Wei Sawdong Three-Tier Waterfall",
    "Rainbow Falls Nongriat",
    "Garden of Caves (Ka Bri Synrang)",
    "Krang Suri Waterfalls Amlarem",
    "Laitlum Canyons",
  ],
  cherrapunji: [
    "Nohkalikai Falls",
    "Double Decker Living Root Bridge",
    "Seven Sisters Falls",
    "Mawsmai Limestone Cave",
    "Arwah Cave",
    "Wei Sawdong Waterfall",
    "Dainthlen Falls",
    "Kynrem Falls",
    "Eco Park Cherrapunji",
  ],
  andaman: [
    "Cellular Jail (Kala Pani) & Light & Sound Show",
    "Radhanagar Beach (Havelock Island / Swaraj Dweep)",
    "Elephant Beach Snorkeling & Water Sports",
    "Ross Island (Netaji Subhash Chandra Bose Island)",
    "North Bay Island (Coral Reefs & Underwater Sea Walk)",
    "Bharatpur Beach (Neil Island / Shaheed Dweep)",
    "Laxmanpur Beach Sunset Point",
    "Chidiya Tapu Sunset Point",
    "Baratang Island Limestone Caves & Mud Volcano",
    "Samudrika Naval Marine Museum",
    "Kalapathar Beach Havelock",
    "Corbyn's Cove Beach Port Blair",
  ],
  puri: [
    "Shree Jagannath Temple Puri",
    "Golden Beach Puri (Blue Flag)",
    "Konark Sun Temple",
    "Gundicha Temple",
    "Chilika Lake Sea Mouth",
    "Raghurajpur Heritage Crafts Village",
    "Swargadwar Beach",
    "Lokanath Temple",
    "Narendra Tank",
    "Baliharachandi Beach & Temple",
    "Pipili Applique Village",
    "Markandeshwar Shiva Temple",
    "Ramachandi Beach & Temple",
    "Alarnatha Temple Brahmagiri",
    "Sudarsan Crafts Museum Puri",
    "Chakratirtha Temple Puri",
  ],
  sikkim: [
    "Tsomgo Lake (Changu Lake)",
    "Nathula Pass",
    "Rumtek Monastery",
    "Gurudongmar Lake",
    "Yumthang Valley of Flowers",
    "Buddha Park of Ravangla",
    "Pelling Skywalk & Chenrezig Statue",
    "MG Marg Gangtok",
    "Baba Harbhajan Singh Temple",
    "Zero Point Yumesamdong",
    "Namchi Chardham (Siddheshwar Dham)",
    "Teesta River White Water Rafting",
    "Kanchenjunga Falls Pelling",
    "Pemayangtse Monastery",
    "Tashiding Monastery",
    "Ganesh Tok & Hanuman Tok",
  ],
  gangtok: [
    "MG Marg Gangtok",
    "Tsomgo Lake",
    "Rumtek Monastery",
    "Nathula Pass",
    "Ban Jhakri Falls and Park",
    "Ganesh Tok Viewpoint",
    "Hanuman Tok",
    "Do Drul Chorten Stupa",
    "Namgyal Institute of Tibetology",
    "Enchey Monastery",
    "Tashi View Point",
    "Gangtok Ropeway Cable Car",
    "Flower Exhibition Centre",
  ],
  darjeeling: [
    "Tiger Hill Sunrise Viewpoint",
    "Darjeeling Himalayan Railway (Toy Train)",
    "Batasia Loop & War Memorial",
    "Ghoom Monastery",
    "Happy Valley Tea Estate",
    "Padmaja Naidu Himalayan Zoological Park",
    "Himalayan Mountaineering Institute",
    "Peace Pagoda & Japanese Temple",
    "Rock Garden Darjeeling",
    "Chowrasta Mall Road",
    "Nightingale Park (Shrubbery)",
    "Singalila National Park",
  ],
  koraput: [
    "Deomali Peak",
    "Duduma Waterfall",
    "Gupteswar Cave Temple",
    "Kolab Dam and Reservoir",
    "Onukadelli Market",
    "Maliguda Tunnel",
    "Sabar Srikhetra Koraput",
    "HAL Museum Sunabeda",
    "Tribal Museum Koraput",
    "Rani Duduma Waterfall",
    "Bagra Waterfall",
    "Jeypore King's Palace Moti Mahal",
    "Balda Caves",
    "Machkund",
    "Putsil Valley Deomali",
    "Gulmi Waterfall",
    "Jalaput Dam",
    "Upper Kolab Botanical Garden",
  ],
  goa: [
    "Baga Beach",
    "Calangute Beach",
    "Dudhsagar Falls",
    "Fort Aguada",
    "Basilica of Bom Jesus",
    "Chapora Fort",
    "Anjuna Beach",
    "Palolem Beach",
    "Shri Mangeshi Temple",
    "Se Cathedral Old Goa",
    "Fontainhas Latin Quarter",
    "Cabo de Rama Fort",
    "Church of Our Lady of the Immaculate Conception",
    "Vagator Beach",
    "Reis Magos Fort",
    "Divar Island",
    "Cotigao Wildlife Sanctuary",
    "Tambdi Surla Temple",
  ],
  jaipur: [
    "Amber Fort",
    "Hawa Mahal",
    "City Palace Jaipur",
    "Jantar Mantar",
    "Nahargarh Fort",
    "Jaigarh Fort",
    "Jal Mahal",
    "Albert Hall Museum",
    "Birla Mandir Jaipur",
    "Patrika Gate",
    "Chokhi Dhani",
    "Galtaji Temple",
    "Sisodia Rani Garden",
    "Chand Baori Abhaneri",
    "Bhangarh Fort",
    "Govind Dev Ji Temple",
  ],
  varanasi: [
    "Kashi Vishwanath Temple",
    "Dashashwamedh Ghat Ganga Aarti",
    "Assi Ghat",
    "Manikarnika Ghat",
    "Sarnath Dhamek Stupa",
    "Banaras Hindu University (BHU) Vishwanath Temple",
    "Ramnagar Fort",
    "Harishchandra Ghat",
    "Tulsi Manas Mandir",
    "Sankat Mochan Hanuman Temple",
    "Chaukhandi Stupa Sarnath",
    "Ganga River Sunrise Boat Ride",
  ],
  agra: [
    "Taj Mahal",
    "Agra Fort",
    "Fatehpur Sikri",
    "Mehtab Bagh",
    "Tomb of I'timad-ud-Daulah (Baby Taj)",
    "Akbar's Tomb Sikandra",
    "Jama Masjid Agra",
    "Sheesh Mahal Agra Fort",
    "Chini Ka Rauza",
    "Moti Masjid Agra Fort",
  ],
  manali: [
    "Solang Valley Adventure Hub",
    "Rohtang Pass",
    "Hadimba Devi Temple",
    "Atal Tunnel",
    "Jogini Waterfalls",
    "Vashisht Hot Water Springs & Temple",
    "Old Manali Cafes & Market",
    "Mall Road Manali",
    "Hampta Pass Trek Trail",
    "Manu Temple",
    "Bhrigu Lake",
    "Naggar Castle",
  ],
  kerala: [
    "Alleppey Backwaters & Houseboat",
    "Munnar Tea Plantations",
    "Athirappilly Waterfalls",
    "Fort Kochi Chinese Fishing Nets",
    "Periyar Wildlife Sanctuary Thekkady",
    "Varkala Cliff & Beach",
    "Kovalam Beach",
    "Wayanad Chembra Peak & Heart Lake",
    "Padmanabhaswamy Temple Trivandrum",
    "Bekal Fort",
    "Kumarakom Bird Sanctuary",
  ],
  munnar: [
    "Tea Museum Munnar",
    "Eravikulam National Park (Nilgiri Tahr)",
    "Mattupetty Dam",
    "Anamudi Peak",
    "Top Station Munnar",
    "Kundala Lake",
    "Attukad Waterfalls",
    "Pothamedu Viewpoint",
    "Kolukkumalai Tea Estate",
    "Lakkam Waterfalls",
  ],
  visakhapatnam: [
    "RK Beach",
    "VMRDA INS Kursura Submarine Museum",
    "Kailasagiri Hilltop Park",
    "Borra Caves",
    "Araku Valley",
    "Simhachalam Temple",
    "Rishikonda Beach",
    "TU 142 Aircraft Museum",
    "Indira Gandhi Zoological Park",
    "Dolphin's Nose Lighthouse",
    "Yarada Beach",
    "Katiki Waterfalls",
    "Bheemili Beach",
    "Thotlakonda Buddhist Complex",
  ],
  paris: [
    "Eiffel Tower",
    "Louvre Museum",
    "Arc de Triomphe",
    "Notre-Dame Cathedral",
    "Sacré-Cœur Basilica",
    "Palace of Versailles",
    "Musée d'Orsay",
    "Panthéon Paris",
    "Sainte-Chapelle",
    "Seine River Cruise",
    "Jardin du Luxembourg",
    "Disneyland Paris",
  ],
  tokyo: [
    "Senso-ji Temple",
    "Tokyo Skytree",
    "Shibuya Crossing",
    "Meiji Jingu Shrine",
    "Tokyo Tower",
    "Shinjuku Gyoen National Garden",
    "Tsukiji Outer Market",
    "TeamLab Planets Tokyo",
    "Akihabara Electric Town",
    "Imperial Palace Tokyo",
    "Ueno Park",
  ],
  bali: [
    "Tanah Lot Temple",
    "Uluwatu Temple & Sunset Amphitheatre",
    "Tegallalang Rice Terraces",
    "Ubud Monkey Forest Sanctuary",
    "Mount Batur Sunrise Volcano Trek",
    "Besakih Great Temple",
    "Nusa Penida Kelingking Beach",
    "Tirta Empul Holy Water Spring",
    "Seminyak Beach",
    "Ulun Danu Beratan Temple",
  ],
  dubai: [
    "Burj Khalifa Observation Deck",
    "The Dubai Mall & Fountain Show",
    "Palm Jumeirah & Atlantis",
    "Dubai Miracle Garden",
    "Dubai Desert Safari Dunes",
    "Museum of the Future",
    "Dubai Marina Walk",
    "Dubai Frame",
    "Gold Souk & Spice Souk Deira",
    "Jumeirah Mosque",
  ],
  maldives: [
    "Male Friday Mosque (Hukuru Miskiy)",
    "Maafushi Island",
    "Banana Reef Dive Site",
    "Hulhumale Beach",
    "National Museum Maldives",
    "Biyadhoo Island Reef",
    "Vaadhoo Island (Bioluminescent Sea of Stars)",
    "Artificial Beach Male",
    "HP Reef Marine Protected Area",
  ],
  singapore: [
    "Marina Bay Sands Skypark & Infinity Pool",
    "Gardens by the Bay (Supertrees & Cloud Forest)",
    "Universal Studios Singapore",
    "Sentosa Island & Siloso Beach",
    "Singapore Zoo & Night Safari",
    "Merlion Park",
    "Jewel Changi Airport (Rain Vortex)",
    "Chinatown & Buddha Tooth Relic Temple",
    "Little India & Sri Veeramakaliamman Temple",
    "Clarke Quay Riverside",
  ],
  bangkok: [
    "The Grand Palace & Temple of the Emerald Buddha",
    "Wat Arun (Temple of Dawn)",
    "Wat Pho (Temple of the Reclining Buddha)",
    "Chatuchak Weekend Market",
    "Chao Phraya River Cruise",
    "Asiatique The Riverfront",
    "Lumphini Park",
    "Siam Paragon & ICONSIAM",
    "Jim Thompson House",
    "Khao San Road",
  ],
  phuket: [
    "Phi Phi Islands Boat Tour",
    "Big Buddha Phuket",
    "Patong Beach & Bangla Road",
    "Wat Chalong Temple",
    "Old Phuket Town Heritage Street",
    "Kata Noi Beach & Karon Viewpoint",
    "Promthep Cape Sunset",
    "James Bond Island (Phang Nga Bay)",
    "Similan Islands Snorkeling",
    "Phuket FantaSea Cultural Theme Park",
  ],
  london: [
    "Big Ben & Palace of Westminster",
    "Tower of London & Tower Bridge",
    "London Eye",
    "British Museum",
    "Buckingham Palace & Changing of the Guard",
    "Westminster Abbey",
    "Hyde Park & Kensington Gardens",
    "Tate Modern & St. Paul's Cathedral",
    "Trafalgar Square & National Gallery",
    "Covent Garden",
  ],
  "new york": [
    "Statue of Liberty & Ellis Island",
    "Central Park",
    "Empire State Building Observation Deck",
    "Times Square & Broadway",
    "Brooklyn Bridge",
    "Metropolitan Museum of Art (The Met)",
    "Top of the Rock (Rockefeller Center)",
    "9/11 Memorial & Museum",
    "High Line Park & Hudson Yards",
    "Grand Central Terminal",
  ],
  rome: [
    "Colosseum",
    "Vatican City & St. Peter's Basilica",
    "Trevi Fountain",
    "Pantheon Rome",
    "Roman Forum & Palatine Hill",
    "Piazza Navona",
    "Spanish Steps",
    "Castel Sant'Angelo",
    "Borghese Gallery & Gardens",
    "Trastevere Neighborhood",
  ],
};

/**
 * Returns iconic attraction seeds for a destination name.
 *
 * @param {string} destination - Destination string
 * @returns {string[]} Array of famous attraction names
 */
const getFamousAttractionSeeds = (destination) => {
  if (!destination || !destination.trim()) return [];
  const norm = destination.toLowerCase().trim();

  for (const [key, seeds] of Object.entries(SEEDS_MAP)) {
    if (norm.includes(key) || key.includes(norm)) {
      return seeds;
    }
  }

  return [];
};

module.exports = {
  getFamousAttractionSeeds,
};
